id: AFCB677FD
title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
  Practice that Unites the Oral, Treasure and Visionary Teachings
type: translation
pechas:
- I67188018
- IFFCE292C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:47.446464
  last_modified_at: 2023-01-04 11:31:47.446478
  collections:
  - Chöje Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I67188018/C375: '1599'
  IFFCE292C/ACB9: '1599'
